<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="c03_InteractingWithIO" Id="{b55b0158-5127-4f7c-9a66-39b78c21b322}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM c03_InteractingWithIO
VAR_INPUT
	Enable 			: BOOL;
END_VAR
VAR_OUTPUT
	isInited : BOOL;
END_VAR
VAR
	sACN_Com : FB_sACN_UDP_Communicator;
		
	sACN_Sender_U111: FB_sACN_SourceExtDmx;
	
	sACN_Receiver_U222:	FB_sACN_Receiver;
	sACN_Receiver_U444:	FB_sACN_ReceiverAndMerger;
	
	LastReceivedPacketNum : UINT;
	i : UINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF NOT isInited THEN
	sACN_Sender_U111.BindExternalDmxArray(Term07.DmxArrayTo_sAcn_U111);
	//sACN_Receiver_U444.BindExternalDmxArray(Term06.DmxLightFixture_Left);
	isInited := TRUE;
END_IF

CallAllFbs(); //with graphical representation of Fbs
	 
IF sACN_Receiver_U222.ReceiveCounter <> LastReceivedPacketNum THEN//New sACN Packet has been received
	LastReceivedPacketNum := sACN_Receiver_U222.ReceiveCounter;
	//Demonstration of how to extract and utilize DMX data from received packets.
	//You alwayes have a direct access to a recieved packete. sACN_Receiver_U444.ReceiveCounter varible can show you if you got the new one.
	IF  sACN_Receiver_U222.ReceivedPacket.AsDataPacket.FL02_VectorFraming = Tc3_sACN.sACN_Params.VECTOR_E131_DATA_PACKET THEN //Received sACN Packet is Data Packet
		FOR i:=1 TO 8 DO
			Term06.DmxLightFixture_Left[i] := sACN_Receiver_U222.ReceivedPacket.AsDataPacket.DL07_PropertyValues[i+1];
			Term06.DmxLightFixture_Right[i]:= sACN_Receiver_U222.ReceivedPacket.AsDataPacket.DL07_PropertyValues[8 + i+1];
		END_FOR
	END_IF
END_IF]]></ST>
    </Implementation>
    <Action Name="CallAllFbs" Id="{fa6d9dd5-12e9-4a55-b247-b6513e630206}">
      <Implementation>
        <CFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCImplementationObject">
                <o n="Items" t="CFCItemList">
                  <l2 n="InnerList">
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">119L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"222"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">120L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"14, 23, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">118L</v>
                    </o>
                    <o t="CFCBoxElement">
                      <o n="Inputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCInputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">159L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">161L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Outputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCOutputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">163L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">165L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Texts" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCText">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"NetworkAdapterNum"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">160L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"ReconnectTime"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">162L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"BindedToNetworkAdapter"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">164L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"BindedAdapterInfo"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">166L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"FB_sACN_UDP_Communicator"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">157L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"sACN_Com"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">158L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Parameters" t="CFCItemList">
                        <l2 n="InnerList" />
                      </o>
                      <n n="PreparedParameters" />
                      <v n="PageArea">0</v>
                      <v n="Bounds">"38, 2, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="EnEno">false</v>
                      <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="Forced">false</v>
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">150L</v>
                    </o>
                    <o t="CFCBoxElement">
                      <o n="Inputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCInputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">55L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">56L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">75L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">77L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">57L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">79L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">81L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Outputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCOutputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">83L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Texts" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCText">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"sAcnCommunicator"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">64L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"Enable"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">65L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"SourceName"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">76L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"CID"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">78L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"sAcnUniverse"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">66L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"PacketPriority"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">80L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"SendingPeriod"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">82L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"SendedPackets"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">84L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"Tc3_sACN.FB_sACN_SourceExtDmx"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">73L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"sACN_Sender_U111"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">74L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Parameters" t="CFCItemList">
                        <l2 n="InnerList" />
                      </o>
                      <n n="PreparedParameters" />
                      <v n="PageArea">0</v>
                      <v n="Bounds">"41, 8, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="EnEno">false</v>
                      <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="Forced">false</v>
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">54L</v>
                    </o>
                    <o t="CFCBoxElement">
                      <o n="Inputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCInputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">19L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">21L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">23L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Outputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCOutputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">25L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">27L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">29L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">31L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Texts" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCText">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"sAcnCommunicator"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">20L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"Enable"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">22L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"sAcnUniverse"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">24L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"isListening"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">26L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"isBindedToExtArray"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">28L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"ReceiveCounter"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">30L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"RecievedPacket"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">32L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"FB_sACN_Receiver"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">17L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"sACN_Receiver_U222"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">18L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Parameters" t="CFCItemList">
                        <l2 n="InnerList" />
                      </o>
                      <n n="PreparedParameters" />
                      <v n="PageArea">0</v>
                      <v n="Bounds">"21, 19, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="EnEno">false</v>
                      <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="Forced">false</v>
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">10L</v>
                    </o>
                    <o t="CFCBoxElement">
                      <o n="Inputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCInputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">34L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">35L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">36L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">50L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Outputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCOutputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">37L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">38L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">39L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">40L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">52L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Texts" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCText">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"sAcnCommunicator"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">41L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"Enable"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">42L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"sAcnUniverse"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">43L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"MergeRule"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">51L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"isListening"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">44L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"isBindedToExtArray"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">45L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"ReceiveCounter"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">46L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"RecievedPacket"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">47L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"ActiveSources"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">53L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"Tc3_sACN.FB_sACN_ReceiverAndMerger"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">48L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"sACN_Receiver_U444"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">49L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Parameters" t="CFCItemList">
                        <l2 n="InnerList" />
                      </o>
                      <n n="PreparedParameters" />
                      <v n="PageArea">0</v>
                      <v n="Bounds">"21, 28, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="EnEno">false</v>
                      <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="Forced">false</v>
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">33L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">143L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"100"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">144L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"24, 15, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">142L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">147L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"T#100ms"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">148L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"22, 16, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">146L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">168L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"E_NetworkAdapters.SLOT_N01"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">169L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"1, 4, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">167L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">172L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"T#5M"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">173L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"9, 5, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">171L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">95L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"sACN_Com"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">96L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"12, 21, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">94L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">99L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"sACN_Com"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">100L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"12, 30, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">98L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">103L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"sACN_Com"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">104L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"22, 10, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">102L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">107L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Enable"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">108L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"13, 22, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">106L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">110L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Enable"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">111L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"23, 11, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">109L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">113L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Enable"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">114L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"13, 31, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">112L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">123L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"E_DmxMergeRules.LVP"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">124L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"8, 33, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">122L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">127L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"444"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">128L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"14, 32, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">126L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">131L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"Tc2_Utilities.STRING_TO_GUID('a3871605-ff16-48b4-b569-d1b9cc2e14dc')"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">132L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"1, 13, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">130L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">135L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"'sACN Source U111 ShowCase03'"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">136L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"14, 12, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">134L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">139L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"111"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">140L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"24, 14, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">138L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">95L</v>
                      <v n="DestPinId">19L</v>
                      <v n="Id">97L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">99L</v>
                      <v n="DestPinId">34L</v>
                      <v n="Id">101L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">103L</v>
                      <v n="DestPinId">55L</v>
                      <v n="Id">105L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">113L</v>
                      <v n="DestPinId">35L</v>
                      <v n="Id">115L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">107L</v>
                      <v n="DestPinId">21L</v>
                      <v n="Id">116L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">110L</v>
                      <v n="DestPinId">56L</v>
                      <v n="Id">117L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">119L</v>
                      <v n="DestPinId">23L</v>
                      <v n="Id">121L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">123L</v>
                      <v n="DestPinId">50L</v>
                      <v n="Id">125L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">127L</v>
                      <v n="DestPinId">36L</v>
                      <v n="Id">129L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">131L</v>
                      <v n="DestPinId">77L</v>
                      <v n="Id">133L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">135L</v>
                      <v n="DestPinId">75L</v>
                      <v n="Id">137L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">139L</v>
                      <v n="DestPinId">57L</v>
                      <v n="Id">141L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">143L</v>
                      <v n="DestPinId">79L</v>
                      <v n="Id">145L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">147L</v>
                      <v n="DestPinId">81L</v>
                      <v n="Id">149L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">168L</v>
                      <v n="DestPinId">159L</v>
                      <v n="Id">170L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">172L</v>
                      <v n="DestPinId">161L</v>
                      <v n="Id">174L</v>
                    </o>
                  </l2>
                </o>
                <n n="ParameterInitializationMethodGenerator" />
                <o n="RoutingPathTable" t="CFCRoutingPathTable">
                  <d2 n="InnerDictionary" ckt="CFCRoutingConnection" cvt="CFCPointList">
                    <o>
                      <v n="ConnectionId">121L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">18</v>
                        <v n="Y">23</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">18</v>
                          <v n="Y">23</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">20</v>
                          <v n="Y">23</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">101L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">18</v>
                        <v n="Y">30</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">18</v>
                          <v n="Y">30</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">20</v>
                          <v n="Y">30</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">105L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">28</v>
                        <v n="Y">10</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">28</v>
                          <v n="Y">10</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">40</v>
                          <v n="Y">10</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">115L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">18</v>
                        <v n="Y">31</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">18</v>
                          <v n="Y">31</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">20</v>
                          <v n="Y">31</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">116L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">18</v>
                        <v n="Y">22</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">18</v>
                          <v n="Y">22</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">20</v>
                          <v n="Y">22</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">145L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">28</v>
                        <v n="Y">15</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">28</v>
                          <v n="Y">15</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">40</v>
                          <v n="Y">15</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">137L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">28</v>
                        <v n="Y">12</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">28</v>
                          <v n="Y">12</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">40</v>
                          <v n="Y">12</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">149L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">28</v>
                        <v n="Y">16</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">28</v>
                          <v n="Y">16</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">40</v>
                          <v n="Y">16</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">129L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">18</v>
                        <v n="Y">32</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">18</v>
                          <v n="Y">32</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">20</v>
                          <v n="Y">32</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">133L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">28</v>
                        <v n="Y">13</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">28</v>
                          <v n="Y">13</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">40</v>
                          <v n="Y">13</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">97L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">18</v>
                        <v n="Y">21</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">18</v>
                          <v n="Y">21</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">20</v>
                          <v n="Y">21</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">141L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">28</v>
                        <v n="Y">14</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">28</v>
                          <v n="Y">14</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">40</v>
                          <v n="Y">14</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">117L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">28</v>
                        <v n="Y">11</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">28</v>
                          <v n="Y">11</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">40</v>
                          <v n="Y">11</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">125L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">18</v>
                        <v n="Y">33</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">18</v>
                          <v n="Y">33</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">20</v>
                          <v n="Y">33</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">170L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">14</v>
                        <v n="Y">4</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">14</v>
                          <v n="Y">4</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">100</v>
                        </o>
                        <o>
                          <v n="X">37</v>
                          <v n="Y">4</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">174L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">14</v>
                        <v n="Y">5</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">14</v>
                          <v n="Y">5</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">37</v>
                          <v n="Y">5</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                  </d2>
                </o>
                <v n="AutoSizeCanvas">true</v>
                <v n="CanvasWidth">59</v>
                <v n="CanvasHeight">36</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCBoxElement">{f5becf35-b1f3-4274-b411-81d4b63a1516}</Type>
              <Type n="CFCConnection">{5ae2e111-ecff-4a21-b647-2d4da63f8db7}</Type>
              <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
              <Type n="CFCInputElement">{d51129f5-df27-4886-99d1-c564d2e2c1f6}</Type>
              <Type n="CFCInputPin">{c994f6e0-311a-4a1c-bc38-75fe34892406}</Type>
              <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
              <Type n="CFCOutputPin">{65582d84-cf18-4ca0-be59-bf5a3d00b8f8}</Type>
              <Type n="CFCPoint">{b3e42b54-b8f2-45d3-825d-747f82f244a0}</Type>
              <Type n="CFCPointList">{584effbc-813e-443a-bf78-ad9c8d49db41}</Type>
              <Type n="CFCRoutingConnection">{93c117eb-0884-403b-b01e-28b89f47e041}</Type>
              <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
              <Type n="CFCText">{72f2b13f-5349-4a8a-bbe6-2bccf3f42179}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="KindOfCall">{77f43dfe-ca6a-4869-828f-7609d8ed6ea6}</Type>
              <Type n="ProcessValueAccess">{88453c7d-d652-4a27-a1b0-a1953be49a5c}</Type>
              <Type n="SetReset">{24449d48-c96a-49c4-b9d1-a4ea34aedce3}</Type>
              <Type n="SetResetRef">{233bc97c-69fe-4d29-b40e-a9a9b854044e}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </CFC>
      </Implementation>
    </Action>
    <LineIds Name="c03_InteractingWithIO">
      <LineId Id="8" Count="14" />
      <LineId Id="43" Count="0" />
      <LineId Id="23" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>